name: Test with Vitest

on:
  workflow_dispatch:

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Run Test Coverage
        run: npm run coverage
